development:
  adapter: postgresql
  database: zumbadmin_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: zumbadmin_test
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>