development:
  adapter: postgresql
  database: zumbadmin_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: zumbadmin_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: zumbadmin_production
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: zumbadmin_stage
  pool: 5
  timeout: 5000